ERROR - 2025-08-09 04:38:46 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-09 04:38:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 04:38:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 04:38:46 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-08-09 04:38:56 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-09 04:38:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 04:38:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 04:38:56 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 05:14:38 --> ErrorException: Undefined array key "url"
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 59.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->insertBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 05:14:39 --> ErrorException: Undefined array key "url"
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 59.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->insertBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 05:14:40 --> ErrorException: Undefined array key "url"
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 59.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->insertBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 05:14:40 --> ErrorException: Undefined array key "url"
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 59.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->insertBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 05:14:51 --> ErrorException: Undefined array key "url"
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 59.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->insertBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 07:37:24 --> TypeError: CodeIgniter\BaseModel::findAll(): Argument #1 ($limit) must be of type int, null given, called in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_ToolsBrand.php on line 44
in SYSTEMPATH\BaseModel.php on line 621.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(44): CodeIgniter\BaseModel->findAll(null, null)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->getBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 07:38:17 --> TypeError: CodeIgniter\BaseModel::findAll(): Argument #1 ($limit) must be of type int, null given, called in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_ToolsBrand.php on line 44
in SYSTEMPATH\BaseModel.php on line 621.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(44): CodeIgniter\BaseModel->findAll(null, null)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->getBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 08:00:43 --> ErrorException: Undefined property: App\Controllers\Workflow_ToolsBrand::$input
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 18.
 1 APPPATH\Controllers\Workflow_ToolsBrand.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Workflow_ToolsBrand::$input', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsBrand.php', 18)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->getBrand()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-08-09 10:09:01 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-09 10:09:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 10:09:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 10:09:01 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-08-09 10:21:49 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-09 10:21:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 10:21:49 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-09 10:21:49 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
