ERROR - 2025-08-11 09:31:16 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-11 09:31:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:31:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:31:16 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-08-11 09:38:59 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-11 09:38:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:38:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:38:59 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:40:46 --> Error: Class "App\Controllers\ToolsCategoryModel" not found
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->getBrand()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:41:28 --> Error: Class "App\Controllers\ToolsCategoryModel" not found
in APPPATH\Controllers\Workflow_ToolsBrand.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsBrand->getBrand()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsBrand))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-08-11 09:44:20 --> mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist in C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\app\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
#6 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
#7 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\projects\codeigniter\jaquar_admin\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-08-11 09:44:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 2 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:44:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 4 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 09:44:20 --> [Caused by] mysqli_sql_exception: Table 'u372271345_petz.pet_tbl' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `breed_tbl`
JOIN `pet_tbl` ON `pet_tbl`.`pet_id` = `breed_tbl`.`pet_id`
WHERE `breed_tbl`.`flag` = 1', [], false)
 5 APPPATH\Controllers\Workflow_Breed.php(27): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_Breed->getBreed()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_Breed))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 10:06:10 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "breed.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('breed.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('breed', [], true)
 3 APPPATH\Controllers\BaseAction.php(33): view('breed')
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BaseAction->breed()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BaseAction))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 11:17:02 --> ErrorException: Undefined array key "category_url"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 139.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "category_url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 139)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->updateCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 11:18:43 --> ErrorException: Undefined array key "category_url"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 139.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "category_url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 139)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->updateCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 11:19:53 --> ErrorException: Undefined array key "category_url"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 139.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "category_url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 139)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->updateCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 11:20:15 --> ErrorException: Undefined array key "category_url"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 139.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "category_url"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 139)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->updateCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 12:28:42 --> ErrorException: Undefined array key "brand_id"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 98.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "brand_id"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 98)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->insertCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 12:29:31 --> ErrorException: Undefined array key "brand_id"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 98.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "brand_id"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 98)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->insertCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 12:29:31 --> ErrorException: Undefined array key "brand_id"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 98.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "brand_id"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 98)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->insertCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-08-11 12:29:58 --> ErrorException: Undefined array key "brand_id"
in APPPATH\Controllers\Workflow_ToolsCategory.php on line 98.
 1 APPPATH\Controllers\Workflow_ToolsCategory.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "brand_id"', 'C:\\xampp\\htdocs\\projects\\codeigniter\\jaquar_admin\\app\\Controllers\\Workflow_ToolsCategory.php', 98)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_ToolsCategory->insertCategory()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Workflow_ToolsCategory))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
